[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
directories = "6.0.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
